# Generated by Django 3.2.2 on 2021-05-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='numReviewes',
            new_name='numReviews',
        ),
    ]
