# Generated by Django 3.2.2 on 2021-09-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_lagfostuff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(default='https://images.unsplash.com/photo-1532795986-dbef1643a596?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fGZvciUyMHNhbGV8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60'),
        ),
    ]
